site_name: DEMOS
repo_name: "democratizingmodels/democratizingmodels.github.io"
repo_url: https://github.com/democratizingmodels/democratizingmodels.github.io
site_url: https://democratizingmodels.github.io/
site_description: Cross-discipline platform on exchange of research models
site_author: DEMOS
copyright: Copyright &copy; 2025
docs_dir: 'docs/'
site_dir: 'site/'

theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  font: false
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - header.autohide
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - content.tabs.link

  social:
    - icon: material/home
      link: 'https://democratizingmodels.github.io/'
    - icon: material/github
      link: 'https://github.com/democratizingmodels'
    - icon: simple/mattermost
      link: 'https://mattermost.web.cern.ch/democratizingmodels/channels/town-square'

extra_css:
  - assets/css/extra.css

extra_javascript:
  - assets/javascript/config.js
  - https://polyfill-fastly.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  # Built-in
  search: {}
  macros: {}
  # Extra
  i18n:
    docs_structure: suffix
    fallback_to_default: true
    reconfigure_material: true
    reconfigure_search: true
    languages:
      - locale: en
        name: English
        build: true
        default: true
        site_name: DEMOS (en)
      - locale: de
        name: Deutsch
        build: true
        nav_translations:
          Home: Startseite
          Consortium: Konsortium
          Overview: Überblick
          Members: Mitglieder
          Objectives: Ziele
          "State of the Art": Stand der Technik
          "Particle Physics": Teilchenphysik
          "Hadron Physics": Hadronenphysik
          "Nuclear Physics": Kernphysik
          "Neutrino Physics": Neutrinophysik
          "Laser Physics": Laserphysik
          "Astroparticle Physics": Astroteilchenphysik
          "Work Packages": Arbeitspakete
          "Pillar 1 - Model Format": "Säule 1 - Modellformat"
          "WP1.1 Harmonizing Models": "WP1.1 Harmonisierung von Modellen"
          "WP1.2 Engines": "WP1.2 Engines"
          "WP1.3 Containers (MaaS)": "WP1.3 Containers (MaaS)"
          "Pillar 2 - Infrastructure": "Säule 2 - Infrastruktur"
          "WP2.1 Front-end": "WP2.1 Front-end"
          "WP2.2 Back-end": "WP2.2 Back-end"
          "WP2.3 Interoperability": "WP2.3 Interoperabilität"
          "Pillar 3 - Community": "Säule 3 - Gemeinschaft"
          "WP3.1 Documentation": "WP3.1 Dokumentation"
          "WP3.2 Showcasing": "WP3.2 Präsentation"
          "WP3.3 Sustainability": "WP3.3 Nachhaltigkeit"
          "Exploitation Plan": Verwertungsplan
          References: Referenzen
        site_name: DEMOS (de)
        site_description: Interdisziplinäre Plattform zum Austausch von Forschungsmodellen
  table-reader: {}
  glightbox: {}
  section-index: {}
  minify:
    minify_html: true
  git-revision-date-localized:
    type: date
    # Required for generated documentation from gen-files
    fallback_to_build_date: true

markdown_extensions:
  # Built-in
  - markdown.extensions.abbr:
  - markdown.extensions.admonition:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.meta:
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      permalink: true
      permalink: "&nbsp;¶"
  # Extra
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:
  - pymdownx.critic:
      mode: accept
  - pymdownx.details:
  - pymdownx.emoji:
      # https://github.com/twitter/twemoji
      # https://raw.githubusercontent.com/facelessuser/pymdown-extensions/master/pymdownx/twemoji_db.py
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      guess_lang: false
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite:
  - pymdownx.keys:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shortener: true
      social_url_shorthand: true
      normalize_issue_symbols: true
      provider: cern
      custom:
        cern:
          host: https://gitlab.cern.ch
          label: GitLab
          type: gitlab
  - pymdownx.mark:
  - pymdownx.progressbar:
  - pymdownx.saneheaders:
  - pymdownx.smartsymbols:
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - docs/.snippets
        - docs/README.md
      auto_append:
        - links.txt
        - abbrs.txt
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde:
  - attr_list:
  - md_in_html:
  - pymdownx.blocks.caption:

nav:
  - Home: index.md
  - Consortium:
    - Overview: consortium/index.md
    - Members: consortium/members.md
  - Objectives: objectives.md
  - State of the Art:
    - Overview: state-of-art/index.md
    - Particle Physics: state-of-art/particle-physics.md
    - Hadron Physics: state-of-art/hadron-physics.md
    - Nuclear Physics: state-of-art/nuclear-physics.md
    - Neutrino Physics: state-of-art/neutrino-physics.md
    - Laser Physics: state-of-art/laser-physics.md
    - Astroparticle Physics: state-of-art/astroparticle-physics.md
  - Work Packages:
    - Overview: work-packages/index.md
    - Pillar 1 - Model Format:
      - Overview: work-packages/pillar1/index.md
      - WP1.1 Harmonizing Models: work-packages/pillar1/wp1-1-harmonizing.md
      - WP1.2 Engines: work-packages/pillar1/wp1-2-engines.md
      - WP1.3 Containers (MaaS): work-packages/pillar1/wp1-3-containers.md
    - Pillar 2 - Infrastructure:
      - Overview: work-packages/pillar2/index.md
      - WP2.1 Front-end: work-packages/pillar2/wp2-1-frontend.md
      - WP2.2 Back-end: work-packages/pillar2/wp2-2-backend.md
      - WP2.3 Interoperability: work-packages/pillar2/wp2-3-interoperability.md
    - Pillar 3 - Community:
      - Overview: work-packages/pillar3/index.md
      - WP3.1 Documentation: work-packages/pillar3/wp3-1-documentation.md
      - WP3.2 Showcasing: work-packages/pillar3/wp3-2-showcasing.md
      - WP3.3 Sustainability: work-packages/pillar3/wp3-3-sustainability.md
  - Exploitation Plan: exploitation.md
  - References: references.md
